apiVersion: v1
kind: Template
metadata:
  name: logstress
objects:
#
# Deployment replicas of heavy-log-stress pods
#
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: heavy-log-stress
  spec:
    replicas: ${{number_heavy_stress_containers}}
    selector:
      matchLabels:
        app: heavy-log-stress
    template:
      metadata:
        labels:
          app: heavy-log-stress
      spec:
        containers:
        - image: registry.fedoraproject.org/fedora
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          imagePullPolicy: Always
          name: low-log-stress
          command: ["/bin/bash"]
          args:
            - -c
            - >
              yum install -y procps;
              yum install -y unzip;
              unzip /go/bin/log-stressor.zip;
              ./log-stressor --msgpersec=${heavy_containers_msg_per_sec}  ;
              echo ".";
              echo "NEVER GET HERE --> this code is for future performance testing";
              echo ".";
              while true; do
                echo "->";
                sleep 60;
              done;
          volumeMounts:
            - name: log-stressor
              mountPath: /go/bin
        volumes:
          - name: log-stressor
            configMap:
              name: log-stressor-binary-zip
#
# Deployment replicas of low-log-stress pods
#
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: low-log-stress
  spec:
    replicas: ${{number_low_stress_containers}}
    selector:
      matchLabels:
        app: low-log-stress
    template:
      metadata:
        labels:
          app: low-log-stress
      spec:
        containers:
        - image: registry.fedoraproject.org/fedora
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          imagePullPolicy: Always
          name: low-log-stress
          command: ["/bin/bash"]
          args:
            - -c
            - >
              yum install -y procps;
              yum install -y unzip;
              unzip /go/bin/log-stressor.zip;
              ./log-stressor --msgpersec=${low_containers_msg_per_sec}  ;
              echo ".";
              echo "NEVER GET HERE --> this code is for future performance testing";
              echo ".";
              while true; do
                echo "->";
                sleep 60;
              done;
          volumeMounts:
            - name: log-stressor
              mountPath: /go/bin
        volumes:
          - name: log-stressor
            configMap:
              name: log-stressor-binary-zip
parameters:
- name: number_heavy_stress_containers
- name: heavy_containers_msg_per_sec
- name: number_low_stress_containers
- name: low_containers_msg_per_sec

